"""Day trading (open to close, flat every night) backtests on daily OHLC bars.

Usage: python3 research/backtests/day.py <data_dir> <output_md>

Only rules that can be decided at the open and exited at the close are tested here,
because free minute data is not reachable from the cloud sandbox. Opening range
breakout and other intraday rules are covered from published research in RESEARCH.md
and will be tested on Alpaca minute bars once the account is connected.
Also includes a recent (2016 to 2026) check of the swing rules on QQQ and VTI.
"""
import sys

import numpy as np
import pandas as pd

from common import load_ohlcv, metrics, rsi, to_markdown, trade_stats
from swing import run_single, stateful_position

COST = 0.0002  # per side
TICKERS = ["qqq", "vti"]
SPLITS = (("2016", "2020"), ("2021", "2026"))


def day_rule_rows(name, df, take, side=1.0):
    """take: boolean Series known at the open. side +1 long, -1 short."""
    oc = df["close"] / df["open"] - 1
    daily = (side * oc - 2 * COST).where(take, 0.0)
    rows = []
    for period, sl in [("full", slice(None))] + [(f"{a} to {b}", slice(a, b)) for a, b in SPLITS]:
        d = daily.loc[sl]
        m = metrics(d, take.loc[sl].astype(float))
        rows.append({"Rule": name, "Period": period, **m, **trade_stats(d[take.loc[sl]])})
    return rows


def day_tests(df, tk):
    prev_close = df["close"].shift(1)
    gap = df["open"] / prev_close - 1
    prev_ret = df["close"].pct_change().shift(1)
    sma200_prev = df["close"].rolling(200).mean().shift(1)
    up_trend = prev_close > sma200_prev
    df = df.iloc[200:]
    gap, prev_ret, up_trend = gap.loc[df.index], prev_ret.loc[df.index], up_trend.loc[df.index]

    rows = []
    every = pd.Series(True, index=df.index)
    rows += day_rule_rows("Long every day, open to close", df, every)
    rows += day_rule_rows("Gap down > 0.5%: buy open, sell close", df, gap < -0.005)
    rows += day_rule_rows("Gap down > 0.5% in uptrend: buy open", df, (gap < -0.005) & up_trend)
    rows += day_rule_rows("Gap up > 0.5%: short open (fade)", df, gap > 0.005, side=-1.0)
    rows += day_rule_rows("Gap up > 0.5%: buy open (go)", df, gap > 0.005)
    rows += day_rule_rows("Prior day < -1%: buy open, sell close", df, prev_ret < -0.01)
    rows += day_rule_rows("Prior day < -1% in uptrend: buy open", df, (prev_ret < -0.01) & up_trend)

    # where does the return come from: overnight vs intraday
    overnight = (df["open"] / df["close"].shift(1) - 1).fillna(0)
    intraday = df["close"] / df["open"] - 1
    decomp = [
        {"Component": "Overnight only (close to next open)", **metrics(overnight)},
        {"Component": "Intraday only (open to close), no costs", **metrics(intraday)},
        {"Component": "Buy and hold", **metrics(df["close"].pct_change().fillna(0))},
    ]
    return (to_markdown(decomp, f"{tk.upper()}: where the return comes from") + "\n"
            + to_markdown(rows, f"{tk.upper()}: open to close day rules ({COST*1e4:.0f} bps per side)"))


def recent_swing(df, tk):
    c = df["close"]
    sma200, sma5, r2 = c.rolling(200).mean(), c.rolling(5).mean(), rsi(c, 2)
    rows = []
    warm = c.index[200:]

    def add(name, pos):
        d, p, t = run_single(c, pos, COST)
        d = d.loc[warm]
        for period, sl in [("full", slice(None))] + [(f"{a} to {b}", slice(a, b)) for a, b in SPLITS]:
            rows.append({"Strategy": name, "Period": period, **metrics(d.loc[sl], p.loc[warm].loc[sl]),
                         **(trade_stats(t) if period == "full" else {})})

    add("Buy and hold", pd.Series(1.0, index=c.index))
    add("200d SMA trend filter", (c > sma200).astype(float))
    add("RSI(2)<10 pullback, exit > 5d SMA", stateful_position((c > sma200) & (r2 < 10), c > sma5))
    return to_markdown(rows, f"{tk.upper()}: swing rules on recent data")


def main(data_dir, out_md):
    out = ["# Day trading backtest results", "",
           "Generated by `research/backtests/day.py`. See `research/RESEARCH.md` for interpretation.", ""]
    for tk in TICKERS:
        df = load_ohlcv(data_dir, tk)
        out.append(day_tests(df, tk))
    out.append("# Recent swing check on ETFs (2016 to 2026)\n")
    for tk in TICKERS:
        out.append(recent_swing(load_ohlcv(data_dir, tk), tk))
    with open(out_md, "w") as f:
        f.write("\n".join(out))
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
